name: nominatim_api_client
description: A client for accessing the Nominatim API. Please note that Client for Nominatim API is unofficial and not endorsed by Nominatim.
version: 0.0.0
repository: https://github.com/tnc1997/dart-nominatim-api-client

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
